name: "Docker Workflow"
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    #build docker
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the Docker image
        working-directory: ./ngx-backend/
        run: docker build -t ruby_app . && docker tag ruby_app:latest xienthomas/ruby-230306-ngx-backend && docker push xienthomas/ruby-230306-ngx-backend:latest
        
